# download-location: /mnt/Storage/HumbleBundle/Games/
cookie-filename: cookies.txt
# alternatively, paste a session cookie from your browser here, in single quotes, to replace normal authentication
session-cookie: ''
username: <enter your username here>
password: <enter your password here>
download-location: \\megatron\mila\Games\Humble Bundle\
chunk-size: 8192000
force_md5: False
write_md5: True
read_md5: True
debug: True

default_headers:
  Accept: application/json
  Accept-Charset: utf-8
  Keep-Alive: True
  X-Requested-By: hb_android_app
  User-Agent: Apache-HttpClient/UNAVAILABLE (java 1.4)

default_params:
  ajax: True

download-platforms:
  ebook: True

file-formats:
  CBZ: True
  PDF: False
  EPUB: False
  PDF (HQ): False
